language: node_js
node_js: stable
cache:
  directories:
    - node_modules
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
notifications:
  email: false
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
before_script:
 - npm install -g angular/cli
 - npm install -g karma
 - npm install
 - ng lint
 - ng build --aot --prod
 - ng serve & ng e2e
script:
 - ng test --watch=false
