language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
sudo: enabled
notifications:
  email: false
env:
  global:
    – DBUS_SESSION_BUS_ADDRESS=/dev/null
	  – DISPLAY=:99.0
	  – CHROME_BIN=chromium-browser
