language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
sudo: enabled
notifications:
  email: false
script: node_modules/karma/bin/karma start ./karma.conf.js
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
